# Generated by Django 5.2.1 on 2026-03-19 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID закладу')),
                ('name', models.CharField(help_text='Повна назва закладу (наприклад, "Пузата Хата")', max_length=255, verbose_name='Назва закладу')),
                ('address', models.CharField(help_text='Текстова адреса (наприклад, "Хрещатик, 25")', max_length=255, verbose_name='Адреса')),
                ('location_lat', models.DecimalField(decimal_places=6, help_text='Географічна широта (від -90 до 90)', max_digits=9, verbose_name='Широта')),
                ('location_lng', models.DecimalField(decimal_places=6, help_text='Географічна довгота (від -180 до 180)', max_digits=9, verbose_name='Довгота')),
                ('country', models.CharField(help_text='Назва країни (наприклад, "Україна")', max_length=100, verbose_name='Країна')),
                ('city', models.CharField(help_text='Назва міста (наприклад, "Київ")', max_length=100, verbose_name='Місто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Заклад',
                'verbose_name_plural': 'Заклади',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Borsch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID борщу')),
                ('name', models.CharField(help_text='Назва страви (наприклад, "Борщ з пампушками")', max_length=255, verbose_name='Назва борщу')),
                ('type_meat', models.CharField(choices=[('no_meat', "Без м'яса"), ('chicken', 'Курка'), ('pork', 'Свинина'), ('beef', 'Яловичина'), ('other', 'Інше')], default='other', help_text="Категорія м'яса у борщі", max_length=20, verbose_name="Тип м'яса")),
                ('price_uah', models.DecimalField(decimal_places=2, help_text='Вартість порції у гривнях (без символів ₴, ≈)', max_digits=10, verbose_name='Ціна (грн)')),
                ('weight_grams', models.IntegerField(help_text='Вага порції у грамах (ціле число)', verbose_name='Вага (г)')),
                ('photo_urls', models.JSONField(blank=True, default=list, help_text='Список URL або шляхів до зображень борщу', verbose_name='URL фотографій')),
                ('rating_salt', models.DecimalField(decimal_places=1, default=0.0, help_text='Середня оцінка солоності (0-10)', max_digits=3, verbose_name='Оцінка: солоність')),
                ('rating_meat', models.DecimalField(decimal_places=1, default=0.0, help_text="Середня оцінка якості м'яса (0-10)", max_digits=3, verbose_name="Оцінка: м'ясо")),
                ('rating_beet', models.DecimalField(decimal_places=1, default=0.0, help_text='Середня оцінка якості буряка (0-10)', max_digits=3, verbose_name='Оцінка: буряк')),
                ('rating_density', models.DecimalField(decimal_places=1, default=0.0, help_text='Середня оцінка густоти (0-10)', max_digits=3, verbose_name='Оцінка: густота')),
                ('rating_aftertaste', models.DecimalField(decimal_places=1, default=0.0, help_text='Середня оцінка післясмаку (0-10)', max_digits=3, verbose_name='Оцінка: післясмак')),
                ('rating_serving', models.DecimalField(decimal_places=1, default=0.0, help_text='Середня оцінка подачі (0-10)', max_digits=3, verbose_name='Оцінка: подача')),
                ('overall_rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Середня загальна оцінка (0-10)', max_digits=3, verbose_name='Загальна оцінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('place', models.ForeignKey(help_text='Заклад, де подається цей борщ', on_delete=django.db.models.deletion.CASCADE, related_name='borsches', to='core.place', verbose_name='Заклад')),
            ],
            options={
                'verbose_name': 'Борщ',
                'verbose_name_plural': 'Борщі',
                'ordering': ['-overall_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Машинозчитуваний код (наприклад, RESTAURANT, CAFE)', max_length=50, unique=True, verbose_name='Код типу')),
                ('label', models.CharField(help_text='Відображувана назва українською (наприклад, "Ресторан")', max_length=100, verbose_name='Назва типу')),
            ],
            options={
                'verbose_name': 'Тип закладу',
                'verbose_name_plural': 'Типи закладів',
                'ordering': ['label'],
                'indexes': [models.Index(fields=['code'], name='core_placet_code_0614ff_idx')],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Категорія закладу з довідника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.placetype', verbose_name='Тип закладу'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID відгуку')),
                ('temp_user_id', models.CharField(blank=True, help_text='ID для тимчасових користувачів (temp_user_...)', max_length=100, verbose_name='Тимчасовий ID')),
                ('message', models.TextField(help_text='Коментар користувача про борщ', verbose_name='Текст відгуку')),
                ('rating_salt', models.DecimalField(decimal_places=1, help_text='Оцінка солоності (0-10)', max_digits=3, verbose_name='Солоність')),
                ('rating_meat', models.DecimalField(decimal_places=1, help_text="Оцінка якості м'яса (0-10)", max_digits=3, verbose_name="М'ясо")),
                ('rating_beet', models.DecimalField(decimal_places=1, help_text='Оцінка якості буряка (0-10)', max_digits=3, verbose_name='Буряк')),
                ('rating_density', models.DecimalField(decimal_places=1, help_text='Оцінка густоти (0-10)', max_digits=3, verbose_name='Густота')),
                ('rating_aftertaste', models.DecimalField(decimal_places=1, help_text='Оцінка післясмаку (0-10)', max_digits=3, verbose_name='Післясмак')),
                ('rating_serving', models.DecimalField(decimal_places=1, help_text='Оцінка подачі (0-10)', max_digits=3, verbose_name='Подача')),
                ('overall_rating', models.DecimalField(decimal_places=1, help_text='Загальна оцінка борщу (0-10)', max_digits=3, verbose_name='Загальна оцінка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата оновлення')),
                ('borsch', models.ForeignKey(help_text='Борщ, до якого належить відгук', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.borsch', verbose_name='Борщ')),
                ('user', models.ForeignKey(blank=True, help_text='Автор відгуку (може бути null для тимчасових користувачів)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, help_text='Унікальний ідентифікатор з Google OAuth (sub)', max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('given_name', models.CharField(help_text="Ім'я з Google профілю", max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, help_text='Прізвище з Google профілю', max_length=100, verbose_name='Прізвище')),
                ('country', models.CharField(blank=True, help_text='Країна проживання (редагується користувачем)', max_length=100, verbose_name='Країна')),
                ('locale', models.CharField(blank=True, help_text='Мова/регіон з Google профілю (наприклад, uk-UA)', max_length=20, verbose_name='Локаль')),
                ('avatar_url', models.URLField(blank=True, help_text='Посилання на фото профілю (Google picture або завантажене)', verbose_name='URL аватара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.OneToOneField(help_text="Пов'язаний обліковий запис Django User", on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
                'ordering': ['given_name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteBorsch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID запису')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('borsch', models.ForeignKey(help_text='Борщ, доданий до обраних', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.borsch', verbose_name='Борщ')),
                ('user', models.ForeignKey(help_text='Користувач, який додав борщ до обраних', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_borsches', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Обраний борщ',
                'verbose_name_plural': 'Обрані борщі',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='core_favori_user_id_eac6ce_idx'), models.Index(fields=['borsch'], name='core_favori_borsch__6e0796_idx')],
                'unique_together': {('user', 'borsch')},
            },
        ),
        migrations.AddIndex(
            model_name='borsch',
            index=models.Index(fields=['place', 'name'], name='core_borsch_place_i_ec072f_idx'),
        ),
        migrations.AddIndex(
            model_name='borsch',
            index=models.Index(fields=['type_meat'], name='core_borsch_type_me_7c778e_idx'),
        ),
        migrations.AddIndex(
            model_name='borsch',
            index=models.Index(fields=['price_uah'], name='core_borsch_price_u_a7260b_idx'),
        ),
        migrations.AddIndex(
            model_name='borsch',
            index=models.Index(fields=['overall_rating'], name='core_borsch_overall_e7149d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name'], name='core_place_name_113002_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='core_place_city_821d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['country'], name='core_place_country_0af246_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['location_lat', 'location_lng'], name='core_place_locatio_94d66c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['borsch', '-created_at'], name='core_review_borsch__5a8e68_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='core_review_user_id_f98aff_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['google_id'], name='core_userpr_google__e448c5_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='core_userpr_user_id_830b32_idx'),
        ),
    ]
